### ISSUE TITLE
Data.csv file can't contain an empty new line.

### ISSUE THREAD

**Issue by Shy** [nealrs/expo#1]
Adding in late submissions via the github editor adds a new line which causes the site to not render due to the existence of a new line.

**Comment by nealrs** [comment]
Don't use the editor, you must use excel and write back out to CSV as noted
in the instructions. 😛

**Comment by Shy** [comment]
I'd have to buy excel. . . 

Ended up just using sublime, but inline github editing would be faster.

**Comment by nealrs** [comment]
Google docs works great too. That's what Swift used here at hackru.
